kind: Deployment
apiVersion: apps/v1
metadata:
  name: grpc-server-deploy
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: iamtanya/grpc-server:latest
          ports:
            - containerPort: 50051
